const constants = {
  CHANGE_TEXT: 'CHANGE_TEXT',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  UNSET_CURRENT_USER: 'UNSET_CURRENT_USER',
  SET_CURRENT_USER_TEXT: 'SET_CURRENT_USER_TEXT',
};

export default constants;